[WIP]インクリメンタルサーチの実装
YUICHIROONUKI/chat-space pull request #8
Opened 2019-04-06 12:00 UTC by YUICHIROONUKI

# WHAT
グループ作成及び編集時のユーザー検索にインクリメンタルサーチを実装。
ユーザーの追加、削除機能を追加。
# WHY
非同期通信によりビューが変わらないので、作動性が上がった。

2019-04-06 12:10 UTC, kuroko918 reviewed
deviseディレクトリ以下に不要なファイルが多々見受けられますので、削除おねがいします。

2019-04-06 12:10 UTC, kuroko918 commented on app/views/groups/_form.html.haml
> +            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
これはリンク先もないので、aタグでなくて良いかと思います。

2019-04-06 12:10 UTC, kuroko918 commented on app/assets/javascripts/user_name.js
> +                  <a class='user-search-remove chat-group-user__btn chat-group-user__btn--remove js-remove-btn'>削除</a>
これはリンク先もないので、aタグでなくて良いかと思います。

2019-04-06 12:10 UTC, kuroko918 commented on app/views/groups/_form.html.haml
> +      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
このlabelタグのforに紐づくinputがないですがlabelタグを使用するのであればきちんと紐付かせましょう！

2019-04-06 12:10 UTC, kuroko918 commented on app/views/groups/_form.html.haml
> +      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
このlabelタグのforに紐づくinputがないですがlabelタグを使用するのであればきちんと紐付かせましょう！

2019-04-06 12:10 UTC, kuroko918 commented on app/views/groups/_form.html.haml
> +        - group.users.reject{|user| user.name == current_user.name}.each do |user|
ここでcurrent_userを除外するのではなく、controllerで行いましょう！

2019-04-07 02:01 UTC, YUICHIROONUKI commented on app/assets/javascripts/user_name.js
> +                  <a class='user-search-remove chat-group-user__btn chat-group-user__btn--remove js-remove-btn'>削除</a>
不要なaタグをdivタグに変更しました。

2019-04-07 02:51 UTC, YUICHIROONUKI commented on app/views/groups/_form.html.haml
> +      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
labelタグにinputタグを紐づかせました。

2019-04-07 03:05 UTC, YUICHIROONUKI commented on app/views/groups/_form.html.haml
> +        - group.users.reject{|user| user.name == current_user.name}.each do |user|
current_userの除外の記述をcontrollerに記述し直しました。

2019-04-07 03:08 UTC, YUICHIROONUKI commented on app/views/groups/_form.html.haml
> +      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
labelタグにinputタグを紐づけました。

2019-04-07 03:11 UTC, yuki-uchida requested changes

2019-04-07 03:11 UTC, yuki-uchida commented on app/assets/javascripts/user_name.js
> +	function buildHTML(user) {
なんのHTMLを作るかわかるような名前だと良いです

2019-04-07 03:16 UTC, YUICHIROONUKI commented on app/assets/javascripts/user_name.js
> +	function buildHTML(user) {
差し込むhtmlの名前をusersListに変更しました。

2019-04-07 03:18 UTC, yuki-uchida commented
LGTMです！

2019-04-07 03:27 UTC, merged